swagger: "2.0"
info:
  description: This is for NCC Group interciew
  title: "Python-api-master"
  version: '1.0.0'
consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      operationId: api.main.home
      tags:
        - home
      summary: Retrieves home message
      description: Displays home message
      responses:
        200:
          description: See a home message

  /users:
    get:
      operationId: api.users.get_users_info
      responses:
        200:
          description: show all users
    post:
      operationId: api.users.add_user
      tags:
        - users
      summary: Adds a new user
      parameters:
        - name: user
          in: body
          description: user info to create
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              email:
                type: string
              first_name:
                type: string
              last_name:
                type: string
              username:
                type: string
      responses:
        200:
          description: Sucessfully create user
        404:
          description: Not Found

  /users/{uuid}:
    get:
      operationId: api.users.get_by_id
      tags:
        - users
      summary: Retrieves user by id
      description: Displays user by id
      parameters:
        - name: uuid
          in: path
          description: retrieve user info
          type: string
          required: true
      responses:
        200:
          description: Successfully display user info
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                email:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                username:
                  type: string
        404:
          description: User not found

    put:
      operationId: api.users.update_email
      tags:
        - users
      summary: Update user email
      description: Update a single user email
      parameters:
        - name: uuid
          in: path
          description: id to update email
          type: string
          required: true
        - name: email
          in: body
          description: field to update
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
      responses:
        204:
          description: Sucessfully updated user email
        400:
          description: Invalid request
